### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by bradleyDean** [jneuendorf/code-annotations#28]
[Enter steps to reproduce:]

1. press ctrl-alt-c twice
2. select "Add annotation with content"
3. Enter a name (for example, "Notes on transfer.create")
4.) press enter (then editor throws an error)

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: [code-annotations](https://github.com/jneuendorf/code-annotations) package 2.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/brad/.atom/packages/code-annotations/lib/annotation-manager.coffee:100

TypeError: Cannot read property 'getPath' of undefined
    at CodeAnnotationNameDialog.onSubmitCallback (/packages/code-annotations/lib/annotation-manager.coffee:100:57)
    at CodeAnnotationNameDialog.module.exports.CodeAnnotationNameDialog._submit (/packages/code-annotations/lib/views/asset-name-dialog.coffee:14:22)
    at /packages/code-annotations/lib/views/dialog.coffee:20:25)
    at CommandRegistry.handleCommandEvent (/snap/atom/144/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/snap/atom/144/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/snap/atom/144/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/snap/atom/144/usr/share/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:34 vim-mode-plus:move-right (input.hidden-input)
  2x -1:33 vim-mode-plus:move-left (input.hidden-input)
     -1:32.4.0 vim-mode-plus:move-right (input.hidden-input)
  4x -1:15.1.0 vim-mode-plus:move-down (input.hidden-input)
     -1:06.3.0 intentions:highlight (input.hidden-input)
     -0:35.2.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  3x -0:34.9.0 vim-mode-plus:move-down (input.hidden-input)
  4x -0:33.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:32.6.0 vim-mode-plus:move-down (input.hidden-input)
  4x -0:29.3.0 vim-mode-plus:move-left (input.hidden-input)
     -0:21 code-annotations:show-commands (input.hidden-input)
     -0:19.1.0 core:move-down (input.hidden-input)
     -0:18.9.0 core:confirm (input.hidden-input)
     -0:18.8.0 code-annotations:add-annotation-with-content (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.has-code-annotations-container)
  2x -0:12.8.0 core:backspace (input.hidden-input)
     -0:08.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.2 
atom-ctags 5.1.2 
atom-typescript 12.3.8 
atom-updater-linux 1.0.6 
autocomplete-ionic-framework 0.2.2 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.3 
code-annotations 2.2.0 
color-picker 2.2.5 
emmet 2.4.3 
goto-definition 1.3.4 
intentions 1.1.5 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap-find-and-replace 4.5.2 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
sync-settings 0.8.5 
tab-to-escape 0.1.0 
teletype 0.10.0 
todo-show 2.1.0 
unsaved-changes 0.1.0 
vim-mode-plus 1.31.1 
vim-surround 0.8.1 
vmp-gutter-annotate-mark 0.3.2 
wakatime 7.0.4 
```

**Comment by jneuendorf** [comment]
Hey, unfortunately I can't reproduce the error. Looking through the code I have an idea though. These two seem to be the reason.

Line 100 is where the error is thrown

https://github.com/jneuendorf/code-annotations/blob/c9e0994fa9f6a6a3d6e45378ee9834eba4b744b4/lib/annotation-manager.coffee#L91-L100

and I guess the `NullPointerException` comes from here

https://github.com/jneuendorf/code-annotations/blob/c9e0994fa9f6a6a3d6e45378ee9834eba4b744b4/lib/annotation-manager.coffee#L328-L337

So seeing this, could it be that your project does NOT have a `.code-annotations` folder AND the editor throwing the error is not contained in any of the project subdirectories (`atom.project.getDirectories()`)? In that case `_initAssetDirectory` would return `null` causing the error.

**Comment by bradleyDean** [comment]
how would I run atom.project.getDirectories() ?
that doesn't look like a terminal command.

**Comment by jneuendorf** [comment]
You can run the command in the chrome developer tools (since Atom is a Chrome 😉). On Linux the shortcut should be `Ctrl+Shift+I` I guess. Or you can use the menu: `View > Developer > Toggle Developer Tools`.
For the path strings run `atom.project.getDirectories().map(dir => dir.getPath())`.

**Comment by bradleyDean** [comment]
Would this error be caused if I had opened multiple folders (from the same Angular project) in separate windows, then added annotations in those separate windows? I noticed that I have .code-annotations files in multiple folders in the same project. Should they only exist at the root-level of the project? 

I think it might have created multiple .code-annotations files because I had opened multiple windows and it just 'assumed' that those were not part of the same project.

**Comment by jneuendorf** [comment]
I haven't tested anything but I think this would **not** be a problem. Your scenario is another issue that's hard to fix, I believe. If you work with multiple windows on the same (git) project (which leads to multiple `.code-annotations` directories, everything should work as long as you keep working that way. A problem would only arise if the project is opened in only 1 window: In that case no code annotations would be detected because the `.code-annotations` directory would be assumed to be directly under the actual (git) project root.

But to be sure you could try to merge the multiple `.code-annotations`- directories into 1 (unless you have dozens of them 😉).
**You should probably back up your project or use a VCS to be able to revert the changes if anything breaks!**
If your _annotations all have different names_ it shouldn't be too hard: Create a `.code-annotations` directory under the actual project's root and copy all assets into that directory. Then create a `.names.cson` file and copy the contents of all `.names.cson` files into that file. The old directories can be deleted.

If the problem persists this is not the reason.

**If it persists...**

In the initial comment you gave the steps for reproduction. Since I couldn't reproduce the problem could you tell me more about your project structure. Maybe I can further narrow down possible reasons for the problem (minimal breaking example).

**Comment by jneuendorf** [comment]
Closing due to inactivity and since `v3` has been out for a while now. @bradleyDean Feel free to reopen if anything new comes up.
